<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Catching - Ymir Tour</title>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <base href="../">

        <link rel="stylesheet" href="book.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:500" rel="stylesheet" type="text/css">

        <link rel="shortcut icon" href="favicon.png">

        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

        <link rel="stylesheet" href="highlight.css">
        <link rel="stylesheet" href="tomorrow-night.css">
        <link rel="stylesheet" href="ayu-highlight.css">

        <!-- Custom theme -->
        
        <link rel="stylesheet" href="custom.css">
        

        

        <!-- Fetch Clipboard.js from CDN but have a local fallback -->
        <script src="https://cdn.jsdelivr.net/clipboard.js/1.6.1/clipboard.min.js"></script>
        <script>
            if (typeof Clipboard == 'undefined') {
                document.write(unescape("%3Cscript src='clipboard.min.js'%3E%3C/script%3E"));
            }
        </script>

        <!-- Fetch JQuery from CDN but have a local fallback -->
        <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
        <script>
            if (typeof jQuery == 'undefined') {
                document.write(unescape("%3Cscript src='jquery.js'%3E%3C/script%3E"));
            }
        </script>

        <!-- Fetch store.js from local - TODO add CDN when 2.x.x is available on cdnjs -->
        <script src="store.js"></script>

    </head>
    <body class="light">
        <!-- Set the theme before any content is loaded, prevents flash -->
        <script type="text/javascript">
            var theme = store.get('mdbook-theme');
            if (theme === null || theme === undefined) { theme = 'light'; }
            $('body').removeClass().addClass(theme);
        </script>

        <!-- Hide / unhide sidebar before it is displayed -->
        <script type="text/javascript">
            var sidebar = store.get('mdbook-sidebar');
            if (sidebar === "hidden") { $("html").addClass("sidebar-hidden") }
            else if (sidebar === "visible") { $("html").addClass("sidebar-visible") }
        </script>

        <div id="sidebar" class="sidebar">
            <ul class="chapter"><li><a href="README.html"><strong>1.</strong> Introduction</a></li><li><a href="hello-world/README.html"><strong>2.</strong> Hello World</a></li><li><ul class="section"><li><a href="hello-world/commentaires.html"><strong>2.1.</strong> Comments</a></li></ul></li><li><a href="primitives/README.html"><strong>3.</strong> Basic programming concepts</a></li><li><ul class="section"><li><a href="primitives/variables.html"><strong>3.1.</strong> Variable and Mutability</a></li><li><a href="primitives/types.html"><strong>3.2.</strong> Data types</a></li><li><a href="primitives/functions.html"><strong>3.3.</strong> Functions</a></li><li><a href="primitives/control.html"><strong>3.4.</strong> Control flows</a></li><li><a href="primitives/operator.html"><strong>3.5.</strong> Operator priority</a></li></ul></li><li><a href="advanced/README.html"><strong>4.</strong> Alias, References and Purity</a></li><li><ul class="section"><li><a href="advanced/references.html"><strong>4.1.</strong> References</a></li><li><a href="advanced/alias.html"><strong>4.2.</strong> Aliases</a></li><li><a href="advanced/copies.html"><strong>4.3.</strong> Copy and Deep copy</a></li><li><a href="advanced/best.html"><strong>4.4.</strong> Best practice</a></li><li><a href="advanced/pure.html"><strong>4.5.</strong> Pure values</a></li></ul></li><li><a href="modules/README.html"><strong>5.</strong> Modules</a></li><li><a href="types/README.html"><strong>6.</strong> User defined types</a></li><li><ul class="section"><li><a href="types/struct.html"><strong>6.1.</strong> Structure</a></li><li><a href="types/enum.html"><strong>6.2.</strong> Enum</a></li><li><a href="types/aka.html"><strong>6.3.</strong> Aka</a></li></ul></li><li><a href="objects/README.html"><strong>7.</strong> Objects</a></li><li><ul class="section"><li><a href="objects/class.html"><strong>7.1.</strong> Class</a></li><li><a href="objects/mutability.html"><strong>7.2.</strong> Mutability</a></li><li><a href="objects/methods.html"><strong>7.3.</strong> Methods</a></li><li><a href="objects/inheritance.html"><strong>7.4.</strong> Inheritance</a></li><li><a href="objects/traits.html"><strong>7.5.</strong> Traits</a></li><li><a href="objects/cast.html"><strong>7.6.</strong> Cast, and dynamic typing</a></li></ul></li><li><a href="functions/README.html"><strong>8.</strong> Function advanced</a></li><li><a href="pattern/README.html"><strong>9.</strong> Pattern matching</a></li><li><a href="errors/main.html"><strong>10.</strong> Error handling</a></li><li><ul class="section"><li><a href="errors/scope_guards.html"><strong>10.1.</strong> Scope guards</a></li><li><a href="errors/catching.html" class="active"><strong>10.2.</strong> Catching</a></li><li><a href="errors/option.html"><strong>10.3.</strong> Exception and option type</a></li><li><a href="errors/fptr_closure.html"><strong>10.4.</strong> Unsafe function pointer</a></li></ul></li><li><a href="templates/README.html"><strong>11.</strong> Templates</a></li><li><ul class="section"><li><a href="templates/special.html"><strong>11.1.</strong> Template types</a></li><li><a href="templates/cte.html"><strong>11.2.</strong> Template values</a></li><li><a href="templates/values.html"><strong>11.3.</strong> Compilation time execution</a></li></ul></li><li><a href="objects/common_traits.html"><strong>12.</strong> Common traits</a></li><li><ul class="section"><li><a href="traits/streamable.html"><strong>12.1.</strong> Streamable</a></li><li><a href="traits/copiable.html"><strong>12.2.</strong> Copiable</a></li><li><a href="traits/disposable.html"><strong>12.3.</strong> With guard and Disposable</a></li><li><a href="traits/hashable.html"><strong>12.4.</strong> Hashable</a></li><li><a href="traits/serialize.html"><strong>12.5.</strong> Packable and Serializable</a></li></ul></li><li><a href="templates/operators.html"><strong>13.</strong> Operator overloading</a></li><li><ul class="section"><li><a href="templates/binary.html"><strong>13.1.</strong> Unary, binary and Comparison</a></li><li><a href="templates/complex_operators.html"><strong>13.2.</strong> Access, contains and iteration</a></li></ul></li><li><a href="version/README.html"><strong>14.</strong> Version</a></li><li><a href="macros/README.html"><strong>15.</strong> Macro</a></li><li><ul class="section"><li><a href="macros/std.html"><strong>15.1.</strong> Std and Core macros</a></li></ul></li><li><a href="documentation/README.html"><strong>16.</strong> Documentation</a></li><li><ul class="section"><li><a href="documentation/types.html"><strong>16.1.</strong> Types</a></li><li><a href="documentation/symbols.html"><strong>16.2.</strong> Symbols</a></li></ul></li></ul>
        </div>

        <div id="page-wrapper" class="page-wrapper">

            <div class="page" tabindex="-1">
                
                <div id="menu-bar" class="menu-bar">
                    <div class="left-buttons">
                        <i id="sidebar-toggle" class="fa fa-bars" title="Toggle sidebar"></i>
                        <i id="theme-toggle" class="fa fa-paint-brush" title="Change theme"></i>
                    </div>

                    <h1 class="menu-title">Ymir Tour</h1>

                    <div class="right-buttons">
                        <a href="print.html">
                            <i id="print-button" class="fa fa-print" title="Print this book"></i>
                        </a>
                    </div>
                </div>

                <div id="content" class="content">
                    <a class="header" href="errors/catching.html#catching-exceptions" id="catching-exceptions"><h1>Catching exceptions</h1></a>
<p>The main idea of exception is the possibility to recover from a
failing program state. In order to do that, another scope guard exits
in <em>Ymir</em>, this scope guard is named <em>catch</em>. The syntax of this scope
guard is relatively close to the other scope guard, and to the pattern
matching. Indeed, this scope guard does not execute an expression but
match over an exception that has been caught. The following code block
present the grammar of the <em>catch</em> scope guard. The
<em>pattern_expression</em> used in this code block are those defined in the
chapter <a href="https://gnu-ymir.github.io/Documentations/en/pattern/">Pattern
matching</a>.</p>
<pre><code class="language-grammar">guarded_scope := '{' expression ((';')? expression)* (';')? '}' guards
guards := (Guard expression)* ('catch' catching_expression)? (Guard expression)*
Guard := 'exit' | 'success' | 'failure'

catching_expression := pattern_var | pattern_call | '_'

pattern_var := (Identifier | '_') ':' (type | '_') ('=' pattern_expression)?
pattern_call := (type | '_') '(' (pattern_argument (',' pattern_argument)*)? ')'
pattern_arguments := (Identifier '-&gt;')? pattern_expression
</code></pre>
<a class="header" href="errors/catching.html#catch-everything" id="catch-everything"><h2>Catch everything</h2></a>
<p><em>Catch</em> scope guard can be used to catch any exception and continue
the execution of the program. In the following example, the <strong><code>main</code></strong>
function calls the <strong><code>foo</code></strong> function, that throws an
<strong><code>&amp;AssertError</code></strong>. The call is guarded by a catch expression, that
catch every kind of <strong><code>Exception</code></strong> (using the <strong><code>_</code></strong> token). Because
the exception of the <strong><code>foo</code></strong> function is caught the <strong><code>main</code></strong>
function is considered safe, and thus cannot throw an exception, this
is why nothing is declared in its prototype. In this example, the
program ends normaly, after exiting the <strong><code>main</code></strong> function.</p>
<pre><code class="language-ymir">import std::io;

def foo (i : i32) 
    throws &amp;AssertError
{
    assert (i &lt; 10, &quot;i must be lower than 10&quot;);
    println (i);
}

def main () {
    println (&quot;Before foo&quot;);
    { 
        foo (10); 
    } catch {
        _ =&gt; {
            println (&quot;Foo failed&quot;);
        }
    }
    println (&quot;After foo&quot;);
}
</code></pre>
<p><br></p>
<p>Results:</p>
<pre><code>Before foo
Foo failed
After foo
</code></pre>
<p><br></p>
<p>A variable pattern can also be used to get the value of the
exception. There is no much change in the following example, in
comparison to the previous one, except that the <strong><code>main</code></strong> function
prints the exception that has been throw by the <strong><code>foo</code></strong> function. In
<em>debug</em> mode (<em>-g</em> option of the compiler), when throwing an
exception, the stack trace is accessible and printed, when printing an
exception. This stack trace (for efficiency reasons) is not created in
<em>release</em> mode.</p>
<pre><code class="language-ymir">import std::io;

def foo (i : i32) 
    throws &amp;AssertError
{
    assert (i &lt; 10, &quot;i must be lower than 10&quot;);
    println (i);
}

def main () {
    println (&quot;Before foo&quot;);
    { 
        foo (10); 
    } catch {
        err : _ =&gt; {
            println (&quot;Foo failed : &quot;, err);
        }
    }
    println (&quot;After foo&quot;);
}
</code></pre>
<p><br></p>
<p>Results:</p>
<pre><code>Before foo
Foo failed : core::exception::AssertError (i must be lower than 10):
╭  Stack trace :
╞═ bt ╕ #1 in function core::exception::AssertError::self (...)
│     ╘═&gt; /home/emile/ymir/Runtime/midgard/core/exception.yr:49
╞═ bt ╕ #2 in function core::exception::abort (...)
│     ╘═&gt; /home/emile/ymir/Runtime/midgard/core/exception.yr:84
╞═ bt ╕ #3 in function main::foo (...)
│     ╘═&gt; /home/emile/Documents/test/ymir/main.yr:7
╞═ bt ╕ #4 in function main (...)
│     ╘═&gt; /home/emile/Documents/test/ymir/main.yr:14
╞═ bt ╕ #5
│     ╘═&gt; /lib/libgyruntime.so:??
╞═ bt ╕ #6 in function main
│     ╘═&gt; /home/emile/Documents/test/ymir/main.yr:10
╞═ bt ╕ #7
│     ╘═&gt; /lib/x86_64-linux-gnu/libc.so.6:??
╞═ bt ═ #8 in function _start
╰
After foo
</code></pre>
<a class="header" href="errors/catching.html#catch-a-specific-exception" id="catch-a-specific-exception"><h2>Catch a specific exception</h2></a>
<p>The content of a <em>catch</em> scope guard is a list of patterns, that can
be used to get a different behavior for different kind of
exception. In the following example, the <strong><code>foo</code></strong> function, can throw
two different kind of exception, <strong><code>&amp;AssertError</code></strong> and
<strong><code>&amp;OutOfArray</code></strong>. The <em>catch</em> of the <strong><code>main</code></strong> function has a
different behavior if the exception that is thrown is a
<strong><code>&amp;AssertError</code></strong> or a <strong><code>&amp;OutOfArray</code></strong>, (by using a variable pattern
for <strong><code>&amp;AssertError</code></strong>, and a call pattern for <strong><code>&amp;OutOfArray</code></strong>).</p>
<pre><code class="language-ymir">import std::io;

def foo (i : [i32]) 
    throws &amp;AssertError, &amp;OutOfArray
{
    assert (i [0] &lt; 10, &quot;i[0] must be lower than 10&quot;);
    println (i);
}

def main () {
    println (&quot;Before foo&quot;);
    { 
        foo ([]); 
    } catch {
        err : &amp;AssertError =&gt; {
            println (&quot;Foo failed : &quot;, err);
        }
        OutOfArray () =&gt; {
            println (&quot;Foo failed, the slice was empty&quot;);
        }
    }
    println (&quot;After foo&quot;);
}
</code></pre>
<p><br></p>
<p>Results:</p>
<pre><code>Before foo
Foo failed, the slice was empty
After foo
</code></pre>
<p><br></p>
<a class="header" href="errors/catching.html#rethrowing-exceptions" id="rethrowing-exceptions"><h2>Rethrowing exceptions</h2></a>
<p><em>Catch</em> scope guard must catch every exceptions that are thrown by the
scope that is guarded. For example, if the <strong><code>main</code></strong> function of the
previous example, was defined as presented in the next code block, the
compiler would have returned an error. Indeed, in this example, the
<strong><code>&amp;OutOfArray</code></strong> exception is not managed by the <em>catch</em> guard.</p>
<pre><code class="language-ymir">def main () {
    println (&quot;Before foo&quot;);
    { 
        foo ([]); 
    } catch {
        err : &amp;AssertError =&gt; {
            println (&quot;Foo failed : &quot;, err);
        }
    }
    println (&quot;After foo&quot;);
}
</code></pre>
<p><br></p>
<p>Errors:</p>
<pre><code class="language-error">Error : the exception &amp;(core::array::OutOfArray) might be thrown but is not caught
 --&gt; main.yr:(13,7)
13  ┃ 		foo ([]); 
    ╋ 		    ^
    ┃ Note : 
    ┃  --&gt; main.yr:(14,4)
    ┃ 14  ┃ 	} catch {
    ┃     ╋ 	  ^^^^^
    ┗━━━━━┻━ 


ymir1: fatal error: 
compilation terminated.
</code></pre>
<p><br></p>
<p>The <strong><code>OutOfArray</code></strong> exception can be rethrown inside the <em>catch</em>
scope guard to remove this error. In that case the stack trace is
still correct, as it is created by the constructor of the
<strong><code>Exception</code></strong> class.</p>
<pre><code class="language-ymir">def main () 
    throws &amp;OutOfArray
{
    println (&quot;Before foo&quot;);
    { 
        foo ([]); 
    } catch {
        err : &amp;AssertError =&gt; {
            println (&quot;Foo failed : &quot;, err);
        }
        x : &amp;OutOfArray =&gt; throw x;
    }
    println (&quot;After foo&quot;);
}
</code></pre>
<a class="header" href="errors/catching.html#catch-as-a-value" id="catch-as-a-value"><h2>Catch as a value</h2></a>
<p>In some cases (many cases), a scope is used to compute a value. In
that circumstance, if an error occurs inside the scope, the value of
the scope is not set, and cannot be used. For example, in the
following source code, the <strong><code>main</code></strong> function tries to initialize a
variable from the value of the <strong><code>foo</code></strong> function. This function is
not safe, and might return no value at all. In order to guarantee,
that the variable <strong><code>x</code></strong> is initialized, and usable no matter what
happened in the <strong><code>foo</code></strong> function, the <em>catch</em> scope guard can be
used as the default value. This is presented as well at line <strong><code>21</code></strong>
to initialize the variable <strong><code>y</code></strong>.</p>
<pre><code class="language-ymir">import std::io;

def foo (i : i32) 
    throws &amp;AssertError
{
    assert (i &lt; 10, &quot;i[0] must be lower than 10&quot;);
    i + 12
}

def main ()
{
    {
        let x = foo (10); 
        println (x);
    } catch {
        _ =&gt; {
            println (&quot;Foo failed&quot;);
        }
    }

    let y = {
        foo (10)
    } catch {
        _ =&gt; {
            42
        }
    }

    println (y);
}
</code></pre>
<p><br></p>
<p>Results:</p>
<pre><code>Foo failed
42
</code></pre>
<p><br></p>
<p>Because, the <em>catch</em> scope guard is a pattern matching, multiple
branch can be entered. In that case, every branch of the <em>catch</em> guard
must share the same type. In the following example, the value <strong><code>y</code></strong>
is set conditionaly, depending on the type of exception that is thrown
by the <strong><code>foo</code></strong> function, or if the function <strong><code>foo</code></strong> succeeds. In
this example, the <strong><code>foo</code></strong> function throws a <strong><code>&amp;OutOfArray</code></strong>
exception, thus the variable <strong><code>y</code></strong> is set to <strong><code>42</code></strong> (value
computed at line <strong><code>19</code></strong>).</p>
<pre><code class="language-ymir">import std::io;

def foo (i : [i32]) -&gt; i32
    throws &amp;AssertError, &amp;OutOfArray
{
    assert (i[0] &lt; 10, &quot;i[0] must be lower than 10&quot;);
    i[0] + 12
}

def main ()
{
    let y = {
        foo ([])
    } catch {
        AssertError () =&gt; {
            11
        }
        OutOfArray () =&gt; {
            42
        }
    }

    println (y);
}
</code></pre>
<p><br></p>
<p>Results:</p>
<pre><code>42
</code></pre>
<a class="header" href="errors/catching.html#catch-along-other-scope-guards" id="catch-along-other-scope-guards"><h2>Catch along other scope guards</h2></a>
<p><em>Catch</em> scope guards can be used along other scope guards, (<em>success</em>,
<em>failure</em> and <em>exit</em>), but there can be only one <em>catch</em> scope guard
per scope . In that case the priority is the following: 1) <em>failure</em>,</p>
<ol start="2">
<li><em>catch</em>, 3) <em>exit</em>. If there is a <em>success</em> scope guard that is
executed, then the <em>catch</em> scope guard cannot be executed, so the
priority over these two guards is not defined.</li>
</ol>
<pre><code class="language-ymir">import std::io;

def foo (i : [i32]) 
    throws &amp;AssertError, &amp;OutOfArray
{
    assert (i [0] &lt; 10, &quot;i[0] must be lower than 10&quot;);
    println (i);
}

def main ()
{
    println (&quot;Before foo&quot;);
    { 
        foo ([]); 
    } catch {
        err : &amp;AssertError =&gt; {
            println (&quot;Foo failed : &quot;, err);
        }
        _ : &amp;OutOfArray =&gt; {
            println (&quot;Out&quot;);
        }
    } success {
        println (&quot;Succ&quot;);
    } failure {
        println (&quot;Fails&quot;);
    } exit {
        println (&quot;Exit&quot;);
    }
    println (&quot;After foo&quot;);
}
</code></pre>
<p><br></p>
<p>Results:</p>
<pre><code>Before foo
Fails
Out
Exit
After foo
</code></pre>
<p><br></p>
<p>The behavior is exactly the same when <em>catch</em> scope guard has a value.</p>
<pre><code class="language-ymir">import std::io;

def foo (i : [i32]) -&gt; i32
    throws &amp;AssertError, &amp;OutOfArray
{
    assert (i[0] &lt; 10, &quot;i[0] must be lower than 10&quot;);
    i[0] + 12
}

def main ()
{
    let y = {
        foo ([])
    } catch {
        AssertError () =&gt; {
            println (&quot;Assert&quot;);
            11
        }
        OutOfArray () =&gt; {
            println (&quot;Out&quot;);
            42
        }
    } failure {
        println (&quot;Fails&quot;);
    } exit {
        println (&quot;Exit&quot;);
    }

    println (y);
}
</code></pre>
<p><br></p>
<p>Results:</p>
<pre><code>Fails
Out
Exit
42
</code></pre>

                </div>

                <!-- Mobile navigation buttons -->
                
                    <a rel="prev" href="errors/scope_guards.html" class="mobile-nav-chapters previous" title="Previous chapter">
                        <i class="fa fa-angle-left"></i>
                    </a>
                

                
                    <a rel="next" href="errors/option.html" class="mobile-nav-chapters next" title="Next chapter">
                        <i class="fa fa-angle-right"></i>
                    </a>
                

            </div>

            
                <a href="errors/scope_guards.html" class="nav-chapters previous" title="You can navigate through the chapters using the arrow keys">
                    <i class="fa fa-angle-left"></i>
                </a>
            

            
                <a href="errors/option.html" class="nav-chapters next" title="You can navigate through the chapters using the arrow keys">
                    <i class="fa fa-angle-right"></i>
                </a>
            

        </div>


        <!-- Local fallback for Font Awesome -->
        <script>
            if ($(".fa").css("font-family") !== "FontAwesome") {
                $('<link rel="stylesheet" type="text/css" href="_FontAwesome/css/font-awesome.css">').prependTo('head');
            }
        </script>

        <!-- Livereload script (if served using the cli tool) -->
        

        

        

        

        <script src="highlight.js"></script>
        <script src="book.js"></script>

        <!-- Custom JS script -->
        
        <script type="text/javascript" src="custom.js"></script>
        

    </body>
</html>
